# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  nginx:
    build:
      context: ./nginx
      args:
        - UID=989
        - GID=1001
    container_name: nginx
    ports:
      - "80:8080"
    restart: unless-stopped
    volumes:
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro,z
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - /mnt/downloads:/downloads:z
  qbittorrent:
    image: docker.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=989
      - PGID=1001
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 8964:8964
      - 8964:8964/udp
    restart: unless-stopped
    volumes:
      - ./qbittorrent/config:/config:z
      - /mnt/downloads:/downloads:z
