FROM docker.io/library/alpine:3.14

ARG UID=1000
ARG GID=1000

RUN addgroup -g $GID -S nginx && \
    adduser -u $UID -S nginx -G nginx

RUN apk add --no-cache nginx nginx-mod-http-dav-ext

RUN mkdir -p /run/nginx && chown -R nginx:nginx /run/nginx

RUN ln -s /dev/stdout /var/log/nginx/access.log && \
    ln -s /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]